# /etc/fail2ban/jail.d/nginx-auth.conf
[nginx-auth-limit]
enabled  = true
filter   = nginx-auth-limit
action   = iptables-multiport[name=nginx-auth, port="http,https", protocol=tcp]
logpath  = /var/log/nginx/error.log
maxretry = 10
findtime = 300
bantime  = 3600
